In [1]:
import torch

In [3]:
W= torch.arange(12,dtype=torch.float32).reshape(4,3)
W

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

### SVD

In [4]:
# W(mxn)=U(mxn)*S(nXn)*V.T(nXn)
# W(4x3)=U(4x3)*S(3X3)*V.T(3X3)
U,S,V=torch.svd(W)


In [5]:
U

tensor([[-0.0835,  0.8325,  0.5319],
        [-0.3137,  0.4490, -0.8066],
        [-0.5438,  0.0656,  0.0176],
        [-0.7739, -0.3179,  0.2571]])

In [7]:
print(S)
print(torch.diag(S))


tensor([2.2447e+01, 1.4641e+00, 5.6755e-07])
tensor([[2.2447e+01, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.4641e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 5.6755e-07]])


In [10]:
V

tensor([[-0.4976, -0.7653, -0.4082],
        [-0.5740, -0.0624,  0.8165],
        [-0.6504,  0.6406, -0.4082]])

In [12]:
U @ torch.diag(S) @ V.t()

tensor([[5.5576e-08, 1.0000e+00, 2.0000e+00],
        [3.0000e+00, 4.0000e+00, 5.0000e+00],
        [6.0000e+00, 7.0000e+00, 8.0000e+00],
        [9.0000e+00, 1.0000e+01, 1.1000e+01]])

### Truncated SVD

In [19]:
print(torch.diag(S))
# S last value is very small so we will truncate it
# Rem that values of the diagonal decreases as we go right  ===> less important so we can truncate them
St=S[:2]
St

tensor([[2.2447e+01, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.4641e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 5.6755e-07]])


tensor([22.4467,  1.4641])

In [16]:
St_diag=torch.diag(St)
print(St_diag)

# It is now of size 2 we need to to be 3*3 so pad by zeros
import torch.nn.functional as F
St_diag = F.pad(St_diag,(0,1,0,1),mode='constant',value=0)
St_diag

tensor([[22.4467,  0.0000],
        [ 0.0000,  1.4641]])


tensor([[22.4467,  0.0000,  0.0000],
        [ 0.0000,  1.4641,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [17]:
U@St_diag@V.t()

tensor([[1.7881e-07, 1.0000e+00, 2.0000e+00],
        [3.0000e+00, 4.0000e+00, 5.0000e+00],
        [6.0000e+00, 7.0000e+00, 8.0000e+00],
        [9.0000e+00, 1.0000e+01, 1.1000e+01]])

Very Small approximateion but fatser if there are thousands of rows and columns